### ISSUE TITLE
Don't escape `/`

### ISSUE THREAD

**Issue by djmitche** [kemitchell/markdown-escape.js#4]
As far as I can tell, `/` is not a special character to markdown.  And `markdown.toHTML(escape('http://foo.com'))`, for example, produces output with spurious `\` characters in it.

Note that, aside from this bug, markdown-escape is identical to https://github.com/edwmurph/escape-markdown, so perhaps consider merging the two.

**Comment by marko-knoebl** [comment]
I think this depends ... it is escapable in commonmark, but it's not in GFM (github-flavored markdown)

see here for the complete sets of escapable characters: https://github.com/wooorm/markdown-escapes/blob/master/index.js

**Comment by kemitchell** [comment]
@djmitche thanks for this issue. Markdown spec chaos strikes again!

I'm trying to think through how to communicate this to users. Perhaps ideally this package would be called `commonmark-escape`. The current name "isn't wrong". But I'm not sure what's rightest.

Perhaps the answer is to surface this difference in `README`, and add an option flag for the replacement, with the default preserving current behavior?

**Comment by djmitche** [comment]
Yeah that might make sense -- I suppose the other repo I mentioned in the first comment then applies to a different flavor of markdown?

**Comment by kemitchell** [comment]
@djmitche nothing against other packages! Quite the opposite.

But I think we should do the best we can in this package, and not rely on others for part of our own story.

**Comment by kemitchell** [comment]
@djmitche I've just spruced up `master` to make the code a bit more approachable. Would you like to do the PR adding a second, optional options Object, with a flag that disables slash escaping?

**Comment by djmitche** [comment]
I can take a look, sure.

**Comment by marko-knoebl** [comment]
I've just worked on this and related issues for a little:

https://github.com/marko-knoebl/markdown-escape.js

See the readme for some examples.

What I've changed:

- a "flavor" can be passed in via an options argument
- the "commonmark" flavor will escape more characters than before - e.g. backticks, dashes, dots
- the "gfm" flavor will not escape slashes anymore - however, it will escape dots
- the "commonmark" flavor will escape "<" as "\<" instead of "&lt;" - this is allowed according to the commonmark spec

If this is useful we can merge some of these back into this repo.

**Comment by djmitche** [comment]
I'll defer to @marko-knoebl!

**Comment by wooorm** [comment]
Sorry to drop into y’all’s mentions: the GFM part of `wooorm/markdown-escapes` is legacy. As of somewhere in 2017, GFM is now based on CM, and both support the same escapes!

**Comment by kemitchell** [comment]
My head hurts!

**Comment by wooorm** [comment]
hah, yeah it’s a mess 😅 Markdown is a mess!

I wasn’t asked to contribute so, sorry to barge in, but maybe my experience here is of use!
I’d say to solve this, you can either go with a naive approach: escape all ASCII punctuation. Which makes sure that it’s 100% not a markdown construct. But the downside is that you’ll have more escapes than needed. The other end is to try and parse markdown, if it’s indeed emphasis, then escape it. Otherwise an escape isn’t needed. That’s way complex.

Somewhere in the middle, but closer to ASTs, is [this monstrosity](https://github.com/remarkjs/remark/blob/master/packages/remark-stringify/lib/escape.js), which was written before GFM based itself on CM, from when it had different rules.

So, as always, it depends! It depends on what the goal of this project is!

**Comment by kemitchell** [comment]
@wooorm thanks so much for weighing in.

That remark-stringify work is truly impressive ... and very dismaying. The last thing I want to do in this tiny little utility package is further complicate the situation, overall.

When I see this much complexity, my instinct is to be very humble and disciplined about changes. I will have a PR shortly.

**Comment by wooorm** [comment]
That makes a lot of sense! 😅 One thing you could do to make it even cleaner is to not escape the closing `>`, `)`, or `]`, escaping the opening is fine!

**Comment by kemitchell** [comment]
PR in #5.
